apiVersion: v2
name: policybot
description: Helm chart for policybot
keywords:
  - istio
  - policybot
sources:
  - https://github.com/istio/bots
version: "0.1.0"
icon: https://github.com/istio/bots/raw/master/policybot/dashboard/static/img/logo.png