name: default
type: welcome
repos:
  - istio/api
  - istio/bots
  - istio/client-go
  - istio/common-files
  - istio/community
  - istio/envoy
  - istio/istio
  - istio/pkg
  - istio/proxy
  - istio/release-builder
  - istio/test-infra
  - istio/tools
  - istio/ztunnel
  - istio/enhancements

resenddays: 90
message: |
  😊 Welcome @{{.Author}}! This is either your first contribution to the Istio **{{.Repo}}** repo, or it's been
  awhile since you've been here.

  You can learn more about the Istio working groups, code of conduct, and contributing guidelines
  by referring to [Contributing to Istio](https://github.com/istio/community/blob/master/CONTRIBUTING.md).

  Thanks for contributing!
