name: istio.io
type: welcome
repos:
  - "istio/istio.io"

resenddays: 90
message: |
  😊 Welcome! This is either your first contribution to the Istio documentation repo, or
  it's been a while since you've been here. A few things you should know:

  - You can learn about how we write and maintain documentation, our style guidelines,
  and the available web site features by visiting [Contributing to the Docs](https://istio.io/latest/docs/releases/contribute/).

  - In the next few minutes, an automatic preview of your change will be built with
  a full copy of the istio.io website. You can find this preview by clicking on
  the **Details** link next to the `deploy/netlify` entry in the status section of this
  page.

  - We care about quality, so we've put in place a number of checks to ensure our documentation
  is top-notch. We do spell checking, sanitize the Markdown, ensure all hyperlinks point to a
  valid location, and more. If your PR doesn't pass one of these checks, you'll see a red X in the
  `lint_istio.io` entry in the status section. Click on the **Details** link to get a list of the 
  problems with your PR. Fix those problems and push an update; this will automatically re-run the 
  tests. Hopefully this time everything will be perfect!

  - Once your changes are accepted and merged into the repository, they will initially show up
  on <https://preliminary.istio.io>. The changes will be published to <https://istio.io>
  the next time we do a major release (which typically happens every 3 months or so). 
  To publish them sooner, add a `cherrypick/release-x.xx` label, where x.xx is the current
  release of Istio.

  Thanks for contributing!
