name: Note about bugs
type: boilerplate
regex: |
  \(NOTE: This is used to report product bugs:
    To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
    To ask questions about how to use Istio, please visit <https://discuss\.istio\.io>
  \)
