name: PR Area selection
type: boilerplate
regex: |
  ^\*\*To help us figure out who should review this PR, please put an X in all the areas that this PR affects\.\*\*

  - \[[ \w]\] +Ambient
  - \[[ \w]\] +Configuration Infrastructure
  - \[[ \w]\] +Docs
  - \[[ \w]\] +Installation
  - \[[ \w]\] +Networking
  - \[[ \w]\] +Performance and Scalability
  - \[[ \w]\] +Policies and Telemetry
  - \[[ \w]\] +Security
  - \[[ \w]\] +Test and Release
  - \[[ \w]\] +User Experience
  - \[[ \w]\] +Developer Infrastructure
