name: PR Release Note
type: boilerplate
regex: |
  ^\*\*Please check any characteristics that apply to this pull request\.\*\*

  - \[[ \w]\] Does not have any \[user-facing\]\(https://github\.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes\) changes\. This may include CLI changes, API changes, behavior changes, performance improvements, etc\.