apiVersion: v1
kind: Secret
metadata:
  name: policybot
type: Opaque
data:
  GITHUB_WEBHOOK_SECRET: {{ .Values.GITHUB_WEBHOOK_SECRET | b64enc | quote }}
  GITHUB_TOKEN: {{ .Values.GITHUB_TOKEN | b64enc | quote }}
  ZENHUB_TOKEN: {{ .Values.ZENHUB_TOKEN | b64enc | quote }}
  GCP_CREDS: {{ .Values.GCP_CREDS | b64enc | quote }}
  SENDGRID_APIKEY: {{ .Values.SENDGRID_APIKEY | b64enc | quote }}
  GITHUB_OAUTH_CLIENT_ID: {{ .Values.GITHUB_OAUTH_CLIENT_ID | b64enc | quote }}
  GITHUB_OAUTH_CLIENT_SECRET: {{ .Values.GITHUB_OAUTH_CLIENT_SECRET | b64enc | quote }}
