apiVersion: v1
kind: Service
metadata:
  name: istio-policybot
  labels:
    app: policybot
spec:
  ports:
  - name: http
    port: 8080
{{- if not .Values.istio }}
    nodePort: 31000
{{- end }}
  selector:
    app: policybot
{{- if not .Values.istio }}
  type: NodePort
{{- else }}
  type: ClusterIP
{{- end }}
