apiVersion: batch/v1
kind: CronJob
metadata:
  name: policybot-labelmgr
  labels:
    app: policybot-labelmgr
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: policybot
          containers:
            - name: policybot
              image: "{{ .Values.image }}"
              imagePullPolicy: "{{ .Values.imagePullPolicy }}"
              args:
                - /policybot
                - labelmgr
                - --config_repo
                - istio/bots/master
                - --config_path
                - policybot/config
              envFrom:
                - secretRef:
                    name: policybot
          restartPolicy: OnFailure
