apiVersion: batch/v1
kind: CronJob
metadata:
  name: policybot-syncmgr-issues
  labels:
    app: policybot-syncmgr-issues
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: policybot
              image: "{{ .Values.image }}"
              imagePullPolicy: "{{ .Values.imagePullPolicy }}"
              args:
                - /policybot
                - syncmgr
                - --config_repo
                - istio/bots/master
                - --config_path
                - policybot/config
                - --filter
                - issues
              envFrom:
                - secretRef:
                    name: policybot
          restartPolicy: OnFailure
