apiVersion: batch/v1
kind: CronJob
metadata:
  name: policybot-milestonemgr
  labels:
    app: policybot-milestonemgr
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: policybot
          containers:
            - name: policybot
              image: "{{ .Values.image }}"
              imagePullPolicy: "{{ .Values.imagePullPolicy }}"
              args:
                - /policybot
                - milestonemgr
                - --config_repo
                - istio/bots/master
                - --config_path
                - policybot/config
              envFrom:
                - secretRef:
                    name: policybot
          restartPolicy: OnFailure
