apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: policybot-flakemgr
  labels:
    app: policybot-flakemgr
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: policybot
              image: "{{ .Values.image }}"
              imagePullPolicy: "{{ .Values.imagePullPolicy }}"
              args:
                - /policybot
                - flakemgr
                - --config_repo
                - istio/bots/master
                - --config_file
                - policybot/policybot.yaml
              envFrom:
                - secretRef:
                    name: policybot
          restartPolicy: OnFailure
