apiVersion: apps/v1
kind: Deployment
metadata:
  name: policybot-server
  labels:
    app: policybot-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policybot-server
  template:
    metadata:
      labels:
        app: policybot-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: policybot
      containers:
        - name: policybot
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
          - containerPort: 8080
          args:
            - /policybot
            - server
            - --config_repo
            - istio/bots/master
            - --config_path
            - policybot/config
            - --https_only
          envFrom:
          - secretRef:
              name: policybot
